# Generated by Django 4.2.7 on 2023-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=100, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID платежа'),
        ),
    ]
